### ISSUE TITLE
[Bug]: Issues importing `@wordpress` packages

### ISSUE THREAD

**Issue by g-elwell** [bigbite/build-tools#82]
### What happened?

Importing `select` from `@wordpress/data` using module imports does not appear to work correctly, resulting in `undefined` when used.

This is affecting both `watch` and `build` bundles, and appears to be related to how the import is handled within the build tools specifically. For example:
```js
// Build Tools

import { select } from "@wordpress/data";

console.log(select)
// select(storeNameOrDescriptor) {
//   return _default_registry__WEBPACK_IMPORTED_MODULE_0__["default"].select(storeNameOrDescriptor);
// }

console.log(wp.data.select)
// ƒ (){return m[t].apply(null,arguments)}


// WP Scripts

import { select } from "@wordpress/data";

console.log(select)
// ƒ (){return m[t].apply(null,arguments)}

console.log(wp.data.select)
// ƒ (){return m[t].apply(null,arguments)}
```

The end result is that attempting to use `select` to pull data, eg via: `select('core').getUsers({ who: 'authors' }))` will return the following:
```js
TypeError: Cannot read properties of undefined (reading 'getUsers')
    at ThemerComponent (ThemerComponent.js:28:1)
    at kt (react-dom.min.js?ver=18.2.0:10:47633)
    at js (react-dom.min.js?ver=18.2.0:10:120746)
    at kl (react-dom.min.js?ver=18.2.0:10:88654)
    at yl (react-dom.min.js?ver=18.2.0:10:88582)
    at vl (react-dom.min.js?ver=18.2.0:10:88445)
    at cl (react-dom.min.js?ver=18.2.0:10:85602)
    at zn (react-dom.min.js?ver=18.2.0:10:32470)
    at dl (react-dom.min.js?ver=18.2.0:10:86098)
    at react-dom.min.js?ver=18.2.0:10:99554
```

In comparison, running the same command via `wp.data.select` or using `wp-scripts` as a build tool will return data.

### Which environments are you experiencing the issue on?

CLI (macOS, Windows, etc)

**Comment by g-elwell** [comment]
I've set up a branch on another repo to aid debugging this issue: https://github.com/bigbite/themer/tree/test/build-tools-import-issue-82

- Run `composer install` and `npm install`
- Run `npm run watch:dev`
- Activate the plugin
- Visit `Settings > Theme Customiser`
- Expect nothing to be rendered and the following error in console:
```
TypeError: Cannot read properties of undefined (reading '__experimentalGetCurrentThemeBaseGlobalStyles')
    at getBaseConfig (ThemerComponent.js:33:1)
    at ThemerComponent (ThemerComponent.js:42:1)
    at kt (react-dom.min.js?ver=18.2.0:10:47633)
    at js (react-dom.min.js?ver=18.2.0:10:120746)
    at kl (react-dom.min.js?ver=18.2.0:10:88654)
    at yl (react-dom.min.js?ver=18.2.0:10:88582)
    at vl (react-dom.min.js?ver=18.2.0:10:88445)
    at cl (react-dom.min.js?ver=18.2.0:10:85602)
    at zn (react-dom.min.js?ver=18.2.0:10:32470)
    at dl (react-dom.min.js?ver=18.2.0:10:86098)
l
```

In `src/editor/components/fields/ThemerComponent.js` L10, `select` is being imported from the module. Switching this to be destructured from `wp.data` on L15 will resolve the issue
